module.exports = {
	heroList: [{
			"ename": 105,
			"cname": "廉颇",
			"title": "正义爆轰",
			"hero_type": 3,
			"iconUrl": "/static/images/1.jpg",
		},
		{
			"ename": 106,
			"cname": "小乔",
			"title": "恋之微风",
			"hero_type": 2,
			"iconUrl": "/static/images/2.jpg",
		},
		{
			"ename": 107,
			"cname": "赵云",
			"title": "苍天翔龙",
			"hero_type": 1,
			"hero_type2": 4,
			"iconUrl": "/static/images/3.jpg",
		},
		{
			"ename": 108,
			"cname": "墨子",
			"title": "和平守望",
			"hero_type": 2,
			"hero_type2": 1,
			"iconUrl": "/static/images/4.jpg",
		},
		{
			"ename": 109,
			"cname": "妲己",
			"title": "魅力之狐",
			"hero_type": 2,
			"iconUrl": "/static/images/5.jpg",
		},
		{
			"ename": 110,
			"cname": "嬴政",
			"title": "王者独尊",
			"hero_type": 2,
			"iconUrl": "/static/images/6.jpg",
		},
		{
			"ename": 111,
			"cname": "孙尚香",
			"title": "千金重弩",
			"hero_type": 5,
			"iconUrl": "/static/images/7.jpg",
		},
		{
			"ename": 112,
			"cname": "鲁班七号",
			"title": "机关造物",
			"hero_type": 5,
			"iconUrl": "/static/images/8.jpg",
		},
		{
			"ename": 113,
			"cname": "庄周",
			"title": "逍遥梦幻",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/9.jpg",
		},
		{
			"ename": 114,
			"cname": "刘禅",
			"title": "暴走机关",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/10.jpg",
		},
		{
			"ename": 115,
			"cname": "高渐离",
			"title": "叛逆吟游",
			"hero_type": 2,
			"iconUrl": "/static/images/11.jpg",
		},
		{
			"ename": 116,
			"cname": "阿轲",
			"title": "信念之刃",
			"hero_type": 4,
			"iconUrl": "/static/images/12.jpg",
		},
		{
			"ename": 117,
			"cname": "钟无艳",
			"title": "野蛮之锤",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/13.jpg",
		},
		{
			"ename": 118,
			"cname": "孙膑",
			"title": "逆流之时",
			"hero_type": 6,
			"hero_type2": 2,
			"iconUrl": "/static/images/14.jpg",
		},
		{
			"ename": 119,
			"cname": "扁鹊",
			"title": "善恶怪医",
			"hero_type": 2,
			"iconUrl": "/static/images/15.jpg",
		},
		{
			"ename": 120,
			"cname": "白起",
			"title": "最终兵器",
			"hero_type": 3,
			"iconUrl": "/static/images/16.jpg",
		},
		{
			"ename": 121,
			"cname": "芈月",
			"title": "永恒之月",
			"hero_type": 2,
			"hero_type2": 3,
			"iconUrl": "/static/images/17.jpg",
		},
		{
			"ename": 123,
			"cname": "吕布",
			"title": "无双之魔",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/18.jpg",
		},
		{
			"ename": 124,
			"cname": "周瑜",
			"title": "铁血都督",
			"hero_type": 2,
			"iconUrl": "/static/images/19.jpg",
		},
		{
			"ename": 125,
			"cname": "元歌",
			"title": "无间傀儡",
			"hero_type": 4,
			"iconUrl": "/static/images/20.jpg",
		},
		{
			"ename": 126,
			"cname": "夏侯惇",
			"title": "不羁之风",
			"hero_type": 3,
			"hero_type2": 1,
			"iconUrl": "/static/images/21.jpg",
		},
		{
			"ename": 127,
			"cname": "甄姬",
			"title": "洛神降临",
			"hero_type": 2,
			"iconUrl": "/static/images/22.jpg",
		},
		{
			"ename": 128,
			"cname": "曹操",
			"title": "鲜血枭雄",
			"hero_type": 1,
			"iconUrl": "/static/images/23.jpg",
		},
		{
			"ename": 129,
			"cname": "典韦",
			"title": "狂战士",
			"hero_type": 1,
			"iconUrl": "/static/images/24.jpg",
		},
		{
			"ename": 130,
			"cname": "宫本武藏",
			"title": "剑圣",
			"hero_type": 1,
			"iconUrl": "/static/images/25.jpg",
		},
		{
			"ename": 131,
			"cname": "李白",
			"title": "青莲剑仙",
			"hero_type": 4,
			"iconUrl": "/static/images/26.jpg",
		},
		{
			"ename": 132,
			"cname": "马可波罗",
			"title": "远游之枪",
			"hero_type": 5,
			"iconUrl": "/static/images/27.jpg",
		},
		{
			"ename": 133,
			"cname": "狄仁杰",
			"title": "断案大师",
			"hero_type": 5,
			"iconUrl": "/static/images/28.jpg",
		},
		{
			"ename": 134,
			"cname": "达摩",
			"title": "拳僧",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/29.jpg",
		},
		{
			"ename": 135,
			"cname": "项羽",
			"title": "霸王",
			"hero_type": 3,
			"iconUrl": "/static/images/30.jpg",
		},
		{
			"ename": 136,
			"cname": "武则天",
			"title": "女帝",
			"hero_type": 2,
			"iconUrl": "/static/images/31.jpg",
		},

		{
			"ename": 137,
			"cname": "司马懿",
			"title": "寂灭之心",
			"hero_type": 4,
			"hero_type2": 2,
			"iconUrl": "/static/images/32.jpg",
		},
		{
			"ename": 139,
			"cname": "老夫子",
			"title": "万古长明",
			"hero_type": 1,
			"iconUrl": "/static/images/33.jpg",
		},
		{
			"ename": 140,
			"cname": "关羽",
			"title": "一骑当千",
			"hero_type": 1,
			"iconUrl": "/static/images/34.jpg",

		},
		{
			"ename": 141,
			"cname": "貂蝉",
			"title": "绝世舞姬",
			"hero_type": 2,
			"hero_type2": 4,
			"iconUrl": "/static/images/35.jpg",
		},
		{
			"ename": 142,
			"cname": "安琪拉",
			"title": "暗夜萝莉",
			"hero_type": 2,
			"iconUrl": "/static/images/36.jpg",
		},
		{
			"ename": 144,
			"cname": "程咬金",
			"title": "热烈之斧",
			"hero_type": 3,
			"hero_type2": 1,
			"iconUrl": "/static/images/37.jpg",
		},
		{
			"ename": 146,
			"cname": "露娜",
			"title": "月光之女",
			"hero_type": 1,
			"hero_type2": 2,
			"iconUrl": "/static/images/38.jpg",
		},
		{
			"ename": 148,
			"cname": "姜子牙",
			"title": "太古魔导",
			"hero_type": 2,
			"iconUrl": "/static/images/39.jpg",
		},
		{
			"ename": 149,
			"cname": "刘邦",
			"title": "双面君主",
			"hero_type": 3,
			"iconUrl": "/static/images/40.jpg",
		},
		{
			"ename": 150,
			"cname": "韩信",
			"title": "国士无双",
			"hero_type": 4,
			"iconUrl": "/static/images/41.jpg",
		},
		{
			"ename": 152,
			"cname": "王昭君",
			"title": "冰雪之华",
			"hero_type": 2,
			"iconUrl": "/static/images/42.jpg",
		},
		{
			"ename": 153,
			"cname": "兰陵王",
			"title": "暗影刀锋",
			"hero_type": 4,
			"iconUrl": "/static/images/43.jpg",
		},
		{
			"ename": 154,
			"cname": "花木兰",
			"title": "传说之刃",
			"hero_type": 1,
			"hero_type2": 4,
			"iconUrl": "/static/images/44.jpg",
		},

		{
			"ename": 155,
			"cname": "艾琳",
			"title": "精灵之舞",
			"hero_type": 5,
			"iconUrl": "/static/images/45.jpg",
		},
		{
			"ename": 156,
			"cname": "张良",
			"title": "言灵之书",
			"hero_type": 2,
			"iconUrl": "/static/images/46.jpg",
		},
		{
			"ename": 157,
			"cname": "不知火舞",
			"title": "明媚烈焰",
			"hero_type": 2,
			"hero_type2": 4,
			"iconUrl": "/static/images/47.jpg",
		},
		{
			"ename": 162,
			"cname": "娜可露露",
			"title": "鹰之守护",
			"hero_type": 4,
			"iconUrl": "/static/images/48.jpg",
		},
		{
			"ename": 163,
			"cname": "橘右京",
			"title": "神梦一刀",
			"hero_type": 4,
			"hero_type2": 1,
			"iconUrl": "/static/images/49.jpg",
		},
		{
			"ename": 166,
			"cname": "亚瑟",
			"title": "圣骑之力",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/50.jpg",
		},
		{
			"ename": 167,
			"cname": "孙悟空",
			"title": "齐天大圣",
			"hero_type": 4,
			"hero_type2": 1,
			"iconUrl": "/static/images/51.jpg",
		},
		{
			"ename": 168,
			"cname": "牛魔",
			"title": "精英酋长",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/52.jpg",
		},
		{
			"ename": 169,
			"cname": "后羿",
			"title": "半神之弓",
			"hero_type": 5,
			"iconUrl": "/static/images/53.jpg",
		},
		{
			"ename": 170,
			"cname": "刘备",
			"title": "仁德义枪",
			"hero_type": 1,
			"iconUrl": "/static/images/54.jpg",
		},
		{
			"ename": 171,
			"cname": "张飞",
			"title": "禁血狂兽",
			"hero_type": 3,
			"hero_type2": 6,
			"iconUrl": "/static/images/55.jpg",
		},
		{
			"ename": 173,
			"cname": "李元芳",
			"title": "王都密探",
			"hero_type": 5,
			"iconUrl": "/static/images/56.jpg",
		},
		{
			"ename": 174,
			"cname": "虞姬",
			"title": "森之风灵",
			"hero_type": 5,
			"iconUrl": "/static/images/57.jpg",
		},
		{
			"ename": 175,
			"cname": "钟馗",
			"title": "虚灵城判",
			"hero_type": 6,
			"hero_type2": 2,
			"iconUrl": "/static/images/58.jpg",
		},

		{
			"ename": 176,
			"cname": "杨玉环",
			"title": "霓裳风华",
			"hero_type": 2,
			"iconUrl": "/static/images/59.jpg",
		},
		{
			"ename": 177,
			"cname": "成吉思汗",
			"title": "苍狼末裔",
			"hero_type": 5,
			"iconUrl": "/static/images/60.jpg",
		},
		{
			"ename": 178,
			"cname": "杨戬",
			"title": "根源之目",
			"hero_type": 1,
			"iconUrl": "/static/images/61.jpg",
		},

		{
			"ename": 179,
			"cname": "女娲",
			"title": "至高创世",
			"hero_type": 2,
			"iconUrl": "/static/images/62.jpg",
		},
		{
			"ename": 180,
			"cname": "哪吒",
			"title": "桀骜炎枪",
			"hero_type": 1,
			"iconUrl": "/static/images/63.jpg",
		},

		{
			"ename": 182,
			"cname": "干将莫邪",
			"title": "淬命双剑",
			"hero_type": 2,
			"iconUrl": "/static/images/64.jpg",
		},
		{
			"ename": 183,
			"cname": "雅典娜",
			"title": "圣域余晖",
			"hero_type": 1,
			"iconUrl": "/static/images/65.jpg",
		},
		{
			"ename": 184,
			"cname": "蔡文姬",
			"title": "天籁弦音",
			"hero_type": 6,
			"iconUrl": "/static/images/66.jpg",
		},
		{
			"ename": 186,
			"cname": "太乙真人",
			"title": "炼金大师",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/67.jpg",
		},

		{
			"ename": 187,
			"cname": "东皇太一",
			"title": "噬灭日蚀",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/68.jpg",
		},
		{
			"ename": 189,
			"cname": "鬼谷子",
			"title": "万物有灵",
			"hero_type": 6,
			"iconUrl": "/static/images/69.jpg",
		},
		{
			"ename": 190,
			"cname": "诸葛亮",
			"title": "绝代智谋",
			"hero_type": 2,
			"iconUrl": "/static/images/70.jpg",
		},

		{
			"ename": 191,
			"cname": "大乔",
			"title": "沧海之曜",
			"hero_type": 6,
			"iconUrl": "/static/images/71.jpg",
		},
		{
			"ename": 192,
			"cname": "黄忠",
			"title": "燃魂重炮",
			"hero_type": 5,
			"iconUrl": "/static/images/72.jpg",
		},
		{
			"ename": 193,
			"cname": "铠",
			"title": "破灭刃锋",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/73.jpg",
		},

		{
			"ename": 194,
			"cname": "苏烈",
			"title": "不屈铁壁",
			"hero_type": 3,
			"hero_type2": 6,
			"iconUrl": "/static/images/74.jpg",
		},
		{
			"ename": 195,
			"cname": "百里玄策",
			"title": "嚣狂之镰",
			"hero_type": 4,
			"iconUrl": "/static/images/75.jpg",
		},
		{
			"ename": 196,
			"cname": "百里守约",
			"title": "静谧之眼",
			"hero_type": 5,
			"hero_type2": 4,
			"iconUrl": "/static/images/76.jpg",
		},

		{
			"ename": 197,
			"cname": "弈星",
			"title": "天元之弈",
			"hero_type": 2,
			"iconUrl": "/static/images/77.jpg",
		},
		{
			"ename": 198,
			"cname": "梦奇",
			"title": "入梦之灵",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/78.jpg",
		},

		{
			"ename": 199,
			"cname": "公孙离",
			"title": "幻舞玲珑",
			"hero_type": 5,
			"iconUrl": "/static/images/79.jpg",
		},
		{
			"ename": 312,
			"cname": "沈梦溪",
			"title": "爆弹怪猫",
			"hero_type": 2,
			"iconUrl": "/static/images/80.jpg",
		},
		{
			"ename": 501,
			"cname": "明世隐",
			"title": "灵魂劫卜",
			"hero_type": 6,
			"iconUrl": "/static/images/81.jpg",
		},
		{
			"ename": 502,
			"cname": "裴擒虎",
			"title": "六合虎拳",
			"hero_type": 4,
			"hero_type2": 1,
			"iconUrl": "/static/images/82.jpg",
		},
		{
			"ename": 503,
			"cname": "狂铁",
			"title": "战车意志",
			"hero_type": 1,
			"iconUrl": "/static/images/83.jpg",
		},
		{
			"ename": 504,
			"cname": "米莱狄",
			"title": "筑城者",
			"hero_type": 2,
			"iconUrl": "/static/images/84.jpg",
		},

		{
			"ename": 505,
			"cname": "瑶",
			"title": "鹿灵守心",
			"hero_type": 6,
			"iconUrl": "/static/images/85.jpg",
		},
		{
			"ename": 506,
			"cname": "云中君",
			"title": "流云之翼",
			"hero_type": 4,
			"hero_type2": 1,
			"iconUrl": "/static/images/86.jpg",
		},
		{
			"ename": 507,
			"cname": "李信",
			"title": "谋世之战",
			"hero_type": 1,
			"iconUrl": "/static/images/87.jpg",
		},
		{
			"ename": 508,
			"cname": "伽罗",
			"title": "破魔之箭",
			"hero_type": 5,
			"iconUrl": "/static/images/88.jpg",
		},
		{
			"ename": 509,
			"cname": "盾山",
			"title": "无尽之盾",
			"hero_type": 6,
			"hero_type2": 3,
			"iconUrl": "/static/images/89.jpg",
		},
		{
			"ename": 510,
			"cname": "孙策",
			"title": "光明之海",
			"hero_type": 3,
			"hero_type2": 1,
			"iconUrl": "/static/images/90.jpg",
		},

		{
			"ename": 511,
			"cname": "猪八戒",
			"title": "无忧猛士",
			"hero_type": 3,
			"iconUrl": "/static/images/93.jpg",
		},
		{
			"ename": 513,
			"cname": "上官婉儿",
			"title": "惊鸿之笔",
			"hero_type": 2,
			"hero_type2": 4,
			"iconUrl": "/static/images/92.jpg",
		},
		{
			"ename": 515,
			"cname": "嫦娥",
			"title": "寒月公主",
			"hero_type": 2,
			"hero_type2": 3,
			"iconUrl": "/static/images/93.jpg",
		},

		{
			"ename": 518,
			"cname": "马超",
			"title": "冷晖之枪",
			"hero_type": 1,
			"hero_type2": 4,
			"iconUrl": "/static/images/94.jpg",
		},

		{
			"ename": 521,
			"cname": "海月",
			"title": "永夜之子",
			"hero_type": 2,
			"iconUrl": "/static/images/95.jpg",
		},

		{
			"ename": 522,
			"cname": "曜",
			"title": "星辰之子",
			"hero_type": 1,
			"iconUrl": "/static/images/96.jpg",
		},

		{
			"ename": 523,
			"cname": "西施",
			"title": "幻纱之灵",
			"hero_type": 2,
			"iconUrl": "/static/images/97.jpg",
		},

		{
			"ename": 524,
			"cname": "蒙犽",
			"title": "烈炮小子",
			"hero_type": 5,
			"iconUrl": "/static/images/98.jpg",
		},

		{
			"ename": 525,
			"cname": "鲁班大师",
			"title": "神匠",
			"hero_type": 6,
			"iconUrl": "/static/images/99.jpg",
		},

		{
			"ename": 527,
			"cname": "蒙恬",
			"title": "秩序统将",
			"hero_type": 1,
			"hero_type2": 3,
			"iconUrl": "/static/images/100.jpg",
		},

		{
			"ename": 528,
			"cname": "澜",
			"title": "鲨之猎刃",
			"hero_type": 4,
			"iconUrl": "/static/images/101.jpg",
		},
		{
			"ename": 529,
			"cname": "盘古",
			"title": "破晓之神",
			"hero_type": 1,
			"iconUrl": "/static/images/102.jpg",
		},
		{
			"ename": 531,
			"cname": "镜",
			"title": "破镜之刃",
			"hero_type": 4,
			"iconUrl": "/static/images/103.jpg",
		},
		{
			"ename": 533,
			"cname": "阿古朵",
			"title": "山林之子",
			"hero_type": 3,
			"iconUrl": "/static/images/104.jpg",
		},

		{
			"ename": 534,
			"cname": "桑启",
			"title": "萤火之旅",
			"hero_type": 6,
			"iconUrl": "/static/images/105.jpg",
		},
		{
			"ename": 536,
			"cname": "夏洛特",
			"title": "玫瑰剑士",
			"hero_type": 1,
			"iconUrl": "/static/images/106.jpg",
		},

		{
			"ename": 537,
			"cname": "司空震",
			"title": "雷霆之王",
			"hero_type": 1,
			"hero_type2": 2,
			"iconUrl": "/static/images/107.jpg",
		},
		{
			"ename": 538,
			"cname": "云缨",
			"title": "燎原之心",
			"hero_type": 1,
			"hero_type2": 4,
			"iconUrl": "/static/images/108.jpg",
		},
		{
			"ename": 540,
			"cname": "金蝉",
			"title": "渡世行者",
			"hero_type": 2,
			"hero_type2": 6,
			"iconUrl": "/static/images/109.jpg",
		},
		{
			"ename": 542,
			"cname": "暃",
			"title": "玉城之子",
			"hero_type": 4,
			"iconUrl": "/static/images/110.jpg",
		},
		{
			"ename": 544,
			"cname": "赵怀真",
			"title": "自在之心",
			"hero_type": 1,
			"iconUrl": "/static/images/111.jpg",
		},
		{
			"ename": 545,
			"cname": "莱西奥",
			"title": "火鹰船长",
			"hero_type": 5,
			"iconUrl": "/static/images/112.jpg",
		},
		{
			"ename": 548,
			"cname": "戈娅",
			"title": "沙海飞舟",
			"hero_type": 5,
			"iconUrl": "/static/images/113.jpg",
		},
	]
}
